### ISSUE TITLE
Should containerSrc be resolved as a URL?

### ISSUE THREAD

**Issue by foolip** [WICG/longtasks#17]
Nothing in https://wicg.github.io/longtasks/#sec-TaskAttributionTiming suggests that it should and as implemented in Blink it's just the raw attribute value, so the current answer is "no," but in many contexts URLs are resolved, so I wonder why not here.

**Comment by spanicker** [comment]
For background, the purpose of containerSrc (and containerId and containerName) is to help the observer identify the iframe / embed etc. Specifically, this is not the "current URL" of the culprit iframe, as we cannot expose that for security reasons.
I'm open to suggestions.
@igrigorik

**Comment by foolip** [comment]
Right, I'm just wondering why the URL isn't resolved, like when `iframe.src` is accessed.

**Comment by foolip** [comment]
In Blink, that'd be `iframe->getURLAttribute(HTMLNames::srcAttr)`.

**Comment by domenic** [comment]
It's an interesting question. Note that `iframe.src` is reflecting the src attribute, whereas this is not; that's why maybe the unprocessed value makes more sense. There's also the question of what base URL the src would be resolved against---e.g., if the node document's base URL changes, then the resolved src does not actually reflect the contents of the iframe any more, which is a little strange.

My interpretation of the current spec is that what you really want is something like `containerOuterHTML`, but we package that up in the form of various serialized attributes since that's a bit nicer. I.e. the purpose is just to allow developers to find the iframe in their document.

**Comment by spanicker** [comment]
I agree with Domenic that unprocessed URL seems a bit more suitable for this case (although no strong opinions, and happy to update if there is consensus).
Yes something like "containerOuterHTML"  is certainly the intention.

**Comment by foolip** [comment]
OK, so if there isn't really a reason to use the URL for anything from scripts but it's just meant to help a human track down the culprit, then the raw attribute value seems fine, and avoid the question of when it is resolved.
